### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by abarlex** [deviantony/docker-elk#715] opened 2022-05-25 18:58 UTC
Attaching to docker-elk-elasticsearch-1, docker-elk-kibana-1, docker-elk-logstash-1, docker-elk-setup-1
docker-elk-setup-1          | -------- Wed May 25 18:52:42 UTC 2022 --------
docker-elk-setup-1          | [+] Waiting for availability of Elasticsearch
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | # A fatal error has been detected by the Java Runtime Environment:
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | #  Internal Error (codeBuffer.cpp:962), pid=35, tid=36
docker-elk-elasticsearch-1  | #  guarantee(sect->end() <= tend) failed: sanity
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | # JRE version:  (18.0+36) (build )
docker-elk-elasticsearch-1  | # Java VM: OpenJDK 64-Bit Server VM (18+36, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
docker-elk-elasticsearch-1  | # Problematic frame:
docker-elk-elasticsearch-1  | # V  [libjvm.so+0x5a70ec]  CodeBuffer::verify_section_allocation()+0x36c
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/elasticsearch/core.35)
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | # An error report file with more information is saved as:
docker-elk-elasticsearch-1  | # /usr/share/elasticsearch/hs_err_pid35.log
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | #
docker-elk-elasticsearch-1  | /usr/share/elasticsearch/bin/elasticsearch-env: line 84:    35 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$LAUNCHERS_CLASSPATH" 

Linux 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
New
[3:57](https://asaplog.slack.com/archives/D03B7N034SF/p1653505031661999)
Docker version 20.10.16, build aa7e414

**Comment by antoineco** [comment] 2022-05-25 19:08
@abarlex did you perform any change to the Elasticsearch Dockerfile, such as installing add-ons?

**Comment by abarlex** [comment] 2022-05-25 19:11
didn't change, did a git clone and ran docker-compose up

**Comment by antoineco** [comment] 2022-05-25 19:28
I've got to admit that I have no idea how to reproduce this.

Our automated tests run in a [similar environment](https://github.com/actions/virtual-environments/blob/ubuntu20/20220515.1/images/linux/Ubuntu2004-Readme.md), and this failure never ever occurred.
The only major difference I see is the kernel version.

Do you have sufficient resources available in your VM? (if running in a VM)
Anything interesting returned by `dmesg` around the time of the failure?

**Comment by abarlex** [comment] 2022-05-25 19:44
I have resources in the VM, what kernel are you using in tests?

**Comment by antoineco** [comment] 2022-05-25 19:47
The one mentioned in the aforementioned link: `5.13.0`.

The latest test run was [4 days ago](https://github.com/deviantony/docker-elk/runs/6536320509?check_suite_focus=true).

**Comment by antoineco** [comment] 2022-05-25 20:03
Hm, strange. I'm quite sure Elastic thoroughly tested Elasticearch on Java 18.
Anyway, glad you found a workaround.

How did you modify the image? Via the included Dockerfile, or did you build your own image from scratch?

**Comment by antoineco** [comment] 2022-05-25 20:29
FYI I just did a test run on [Ubuntu 22.04](https://github.com/actions/virtual-environments/blob/ubuntu22/20220522.1/images/linux/Ubuntu2204-Readme.md), which runs the Linux 5.15.0 kernel: https://github.com/deviantony/docker-elk/actions/runs/2386932270

No error

**Comment by antoineco** [comment] 2022-06-02 05:45
Closing due to the lack of reproducibility.

Feel free to reopen if the issue persists, with as much information as possible about the environment to allow me to reproduce on my side.

**Closed by antoineco** 2022-06-02 05:45 UTC
Labels: elasticsearch
