### ISSUE TITLE
Default password (changeme) not correctly set

### ISSUE THREAD

**Issue by jsolla** [deviantony/docker-elk#722] opened 2022-06-01 22:34 UTC
### Problem description

Default password (changeme) is not correctly set, and 'changeme' (with quotes) is set instead.

Running the following command:
```console
docker-compose config | grep  "changeme"
```

Gives the following strings as result of parsing the .env file:
```console
  ELASTIC_PASSWORD: '''changeme'''
  KIBANA_SYSTEM_PASSWORD: '''changeme'''
  LOGSTASH_INTERNAL_PASSWORD: '''changeme'''
  ELASTIC_PASSWORD: '''changeme'''
  KIBANA_SYSTEM_PASSWORD: '''changeme'''
  LOGSTASH_INTERNAL_PASSWORD: '''changeme'''
```

It seems like docker-compose is escaping the quotes found in the [.env ](https://github.com/deviantony/docker-elk/blob/main/.env) file, where variable values are assigned as follows: 

```console
ELASTIC_PASSWORD='changeme'
LOGSTASH_INTERNAL_PASSWORD='changeme'
KIBANA_SYSTEM_PASSWORD='changeme'
```

After running command:
```console
docker-compose up
```
Containers are created/launched as expected, but when opening the web browser or using curl,etc the default expected password **changeme** doesn't work but **'changeme'** works fine instead.

#### Docker setup

```console
$ docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.4
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        


```

```console
$ docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by antoineco** [comment] 2022-06-02 05:39
Thanks for the issue report. We are aware of this behaviour, it's been reported several times already and is caused by a bug in older versions of Compose.

Please use a supported version of Compose.

Closing as duplicate of #698

**Comment by jsolla** [comment] 2022-06-02 09:09
Is it possible to add a warning on the "readme" of the project so people is aware of the issue and don't report it over and over again?

**Comment by antoineco** [comment] 2022-06-02 10:20
I believe we do?

> ## Requirements
>
> ### Host setup
>
>* Docker Compose version **1.26.0** or newer (including Compose V2)

Also the aforementioned issue is pinned 📌

**Closed** 2022-06-02 10:20 UTC
Labels: compose

**Comment by antoineco** [comment] 2022-06-02 10:23
I believe we do?

> ## Requirements
>
> ### Host setup
>
>* Docker Compose version **1.26.0** or newer (including Compose V2)

We could add the word "Warning" but if people don't scroll to the requirements I doubt they will see it, no matter how many warnings we add there. (I could be wrong, just talking from experience writing docs.)

Also the aforementioned issue is pinned 📌 so when you click **Issues** it should appear at the very top. Hard to miss!
