### ISSUE TITLE
Add elasticsearch container as a cluster?

### ISSUE THREAD

**Issue by WeiWeiWesley** [deviantony/docker-elk#75] opened 2016-10-20 06:45 UTC
hello~
## here is my docker-compose.yml

``` yml
elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.node.name="es1" -Des.cluster.name="mycluster" -Des.network.host=_eth0_ -Des.network.publish_host=192.168.153.40 -Des.discovery.zen.ping.unicast.hosts=192.168.153.40:9200,192.168.153.40:9400 -Des.discovery.zen.minimum_master_nodes=1
    ports:
    - "9200:9200"
    - "9300:9300"


logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5001:5001" 
  links:
    - elasticsearch

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
```

**Comment by deviantony** [comment] 2016-10-23 19:38
Hello, never tried to manage more than one Elasticsearch container, sorry.

Maybe somebody in the community actually did that. I'll leave it open for now, to see if anybody can give you more information.

**Comment by antoineco** [comment] 2017-03-14 12:41
I think this fits into the discussion in #33 about extensibility.

ES clustering is a whole separate topic which is covered in details in the ES documentation. This project should be easy enough to extend for anyone who already knows how to configure an ES cluster.

If people feel that they need examples I suggest we create wiki page for more advanced setups like this one.

**Comment by antoineco** [comment] 2017-03-14 12:54
Duplicate of #40

**Closed by antoineco** 2017-03-14 12:54 UTC
Labels: elasticsearch, help wanted, question
