### ISSUE TITLE
docker-compose start kibana failed!--No such file or directory/usr/bin/env: bash

### ISSUE THREAD

**Issue by jacktang168** [deviantony/docker-elk#36] opened 2016-01-24 06:59 UTC
I am use docker-machine on windows7 ,all of ELK can be up,but kibana,some error logs show for me:
```
$ docker-compose.exe up
dockerelk_elasticsearch_1 is up-to-date
Starting dockerelk_logstash_1
Creating dockerelk_kibana_1
Attaching to dockerelk_elasticsearch_1, dockerelk_logstash_1, dockerelk_kibana_1
: No such file or directory/usr/bin/env: bash
```
use docker logs , some errors show for me:
```
$ docker logs 0f4a58ad6b89
: No such file or directory
```

**Comment by shailesha** [comment] 2016-02-08 16:41
Hi,

I am also facing exactly the same issue. did you find the solution to this problem?

**Comment by rzijp** [comment] 2016-02-18 17:39
Ran into the same problem, and found a solution. 
The issue is related to windows vs. UNIX line endings. According to [this](http://stackoverflow.com/questions/22301956/error-with-gradlew-usr-bin-env-bash-no-such-file-or-directory) post it is best to change a git setting to not convert line endings (`git config core.autocrlf false`) before cloning onto a Windows environment. For me this trick didn't fix it though, but loading the kibana/entrypoint.sh file into an editor (notepad++) and converting to UNIX format worked.

**Comment by deviantony** [comment] 2016-03-15 01:59
I can't find what is the problem here, will leave the issue open as it seems that it affects multiple users. Could everyone precise its configuration (OS, docker version, compose version) ?

**Comment by rzijp** [comment] 2016-03-21 16:20
Windows 7 Enterprise SP1
```
$ docker-machine.exe version
docker-machine.exe version 0.6.0, build e27fb87

$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

**Comment by deviantony** [comment] 2016-03-21 21:07
So this issue seems related to Windows, thanks for pointing a solution @rzijp, I'll let this issue open for the other users who may have the same problem.

**Comment by jmkgreen** [comment] 2016-05-19 08:39
This should be documented in absence of a fix - I've just hit this on Windows 10.

**Comment by deviantony** [comment] 2016-05-19 08:48
@jmkgreen Did you tried the solution proposed by rzijp?

**Comment by jmkgreen** [comment] 2016-05-19 08:52
@deviantony yes, worked. I also had to `docker-compose build` before "upping" for the change to be recognised.

**Comment by swerfel** [comment] 2016-08-26 09:27
It was a good idea to let this issue open, it helped me a lot.
Here is the summary, because most people start reading from the last post:
This problem occurs because of line endings on windows. After a clone I
* replaced all `\r\n` line endings with `\n` in `./kibana/entrypoint.sh` with notepad++ (extended search and replace)
* started `docker-compose build` to rebuild the kibana image again, before starting it with `docker-compose up `(`-d`)

(btw: thanks for this project)

**Comment by deviantony** [comment] 2016-09-25 20:28
Thanks to @matulko we may have a fix for this issue ! Could anybody here retry on Windows now to check if the problem still exists?

**Comment by swerfel** [comment] 2016-10-05 14:10
after clean clone and running `docker-compose up` no errors occure. Kibana site can be loaded. It looks like the issue is fixed! Thank you!

**Comment by deviantony** [comment] 2016-10-05 19:36
Perfect ! Thanks again to @matulko :trophy:

**Closed by deviantony** 2016-10-05 19:36 UTC
Labels: docker-machine, windows, workaround
