### ISSUE TITLE
Kibana won't start when the trial license expires

### ISSUE THREAD

**Issue by ewitkop-panw** [deviantony/docker-elk#628] opened 2021-10-15 23:16 UTC
### Problem description
License expired

### Extra information

elasticsearch_1  | {"type": "server", "timestamp": "2021-10-15T23:14:47,975Z", "level": "ERROR", "component": "o.e.x.s.a.f.SecurityActionFilter", "cluster.name": "docker-cluster", "node.name": "b75d7c7a50b9", "message": "blocking [cluster:monitor/nodes/stats] operation due to expired license. Cluster health, cluster stats and indices stats \noperations are blocked on license expiration. All data operations (read and write) continue to work. \nIf you have a new license, please update it. Otherwise, please reach out to your support contact.", "cluster.uuid": "l6Sld-zwTASMTwV4nLRhEw", "node.id": "OGZ70chtQIOu89uzBphQeA"  }

#### Docker setup

```console
$ docker version

[OUTPUT HERE]
```

```console
$ docker-compose version

[OUTPUT HERE]
```

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```

**Comment by ewitkop-panw** [comment] 2021-10-15 23:38
It says:

*After this license expires, you can continue using the free features
seamlessly, without losing any data.*

*However Kibana won't start at all.  So the readme should state that you
need to get off the trial license and move over to basic, early on. *

On Fri, Oct 15, 2021 at 7:18 PM Antoine Cotten ***@***.***>
wrote:

> I think that's exactly what the very first part of the README states?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_deviantony_docker-2Delk_issues_628-23issuecomment-2D944801921&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=iDbFuHUkGNVmY3RVAhoT7gM2krMf3COrRANhzurJyy0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMNB64A343PI4NHHFGRXH2TUHCZDXANCNFSM5GC5UNKA&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=aMPOUsz_XmmKsDKhN-8Cpi80-8sLa3CwwXNW7v9VOyM&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=YRxpbK4iPluZnMz_byrxGpq0zEYzLnu_g9yVuBZUAaw&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=P5cFVmibsa-XLHwGyQ2CgQn1IB9A3vPgqEQZMu9LS3o&e=>.
>
>


-- 


Erik Witkop  |  DOD Systems Engineer | PCNSE CISSP GPEN

Palo Alto Networks  |  Boston, MA |  USA

Mobile: 603-490-3737  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>


<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by e-mail.
Any unauthorized use or distribution of the content of this message is
prohibited.

**Comment by ewitkop-panw** [comment] 2021-10-15 23:41
These instructions are pretty cool.

https://ospaarmann.medium.com/tidbits-solving-the-elasticsearch-x-pack-license-issue-in-docker-d15bb22d82fd



On Fri, Oct 15, 2021 at 7:37 PM Erik Witkop ***@***.***>
wrote:

> It says:
>
> *After this license expires, you can continue using the free features
> seamlessly, without losing any data.*
>
> *However Kibana won't start at all.  So the readme should state that you
> need to get off the trial license and move over to basic, early on. *
>
> On Fri, Oct 15, 2021 at 7:18 PM Antoine Cotten ***@***.***>
> wrote:
>
>> I think that's exactly what the very first part of the README states?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_deviantony_docker-2Delk_issues_628-23issuecomment-2D944801921&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=iDbFuHUkGNVmY3RVAhoT7gM2krMf3COrRANhzurJyy0&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMNB64A343PI4NHHFGRXH2TUHCZDXANCNFSM5GC5UNKA&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=aMPOUsz_XmmKsDKhN-8Cpi80-8sLa3CwwXNW7v9VOyM&e=>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=YRxpbK4iPluZnMz_byrxGpq0zEYzLnu_g9yVuBZUAaw&e=>
>> or Android
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=bNGYvrQaLXxaelhZ3_MDlReGckp71DWj2X3rWmhenkQ&s=P5cFVmibsa-XLHwGyQ2CgQn1IB9A3vPgqEQZMu9LS3o&e=>.
>>
>>
>
>
> --
>
>
> Erik Witkop  |  DOD Systems Engineer | PCNSE CISSP GPEN
>
> Palo Alto Networks  |  Boston, MA |  USA
>
> Mobile: 603-490-3737  | www.paloaltonetworks.com
> <https://www.paloaltonetworks.com/>
>
>
> <https://www.paloaltonetworks.com/>
> <https://www.linkedin.com/company/palo-alto-networks>
> <https://www.facebook.com/PaloAltoNetworks/>
> <https://twitter.com/PaloAltoNtwks>
>
> The content of this message is the proprietary and confidential property
> of Palo Alto Networks, and should be treated as such. If you are not the
> intended recipient and have received this message in error, please delete
> this message from your computer system and notify me immediately by e-mail.
> Any unauthorized use or distribution of the content of this message is
> prohibited.
>
>
>
>

-- 


Erik Witkop  |  DOD Systems Engineer | PCNSE CISSP GPEN

Palo Alto Networks  |  Boston, MA |  USA

Mobile: 603-490-3737  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>


<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by e-mail.
Any unauthorized use or distribution of the content of this message is
prohibited.

**Comment by antoineco** [comment] 2021-10-15 23:44
OK the fact that Kibana doesn't start at all is unexpected and worth mentioning. Some features are disabled but all components _should_ be able to run.

Is there any error message in the logs of the Kibana container? Something that could help me figure how to assist and what to document?

**Comment by ewitkop-panw** [comment] 2021-10-15 23:56
concurrent.FutureTask.run(FutureTask.java:264) [?:?]",

elasticsearch_1  | "at
org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[?:?]",

elasticsearch_1  | "at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[?:?]",

elasticsearch_1  | "at java.lang.Thread.run(Thread.java:831) [?:?]"] }

elasticsearch_1  | {"type": "server", "timestamp":
"2021-10-15T23:54:32,475Z", "level": "ERROR", "component":
"o.e.x.s.a.f.SecurityActionFilter", "cluster.name": "docker-cluster", "
node.name": "8bd79f150dae", "message": "blocking
[cluster:monitor/nodes/stats] operation due to expired license. Cluster
health, cluster stats and indices stats \noperations are blocked on license
expiration. All data operations (read and write) continue to work. \nIf you
have a new license, please update it. Otherwise, please reach out to your
support contact.", "cluster.uuid": "l6Sld-zwTASMTwV4nLRhEw", "node.id":
"OGZ70chtQIOu89uzBphQeA"  }

elasticsearch_1  | {"type": "server", "timestamp":
"2021-10-15T23:54:32,475Z", "level": "ERROR", "component":
"o.e.x.m.c.n.NodeStatsCollector", "cluster.name": "docker-cluster", "
node.name": "8bd79f150dae", "message": "collector [node_stats] failed to
collect data", "cluster.uuid": "l6Sld-zwTASMTwV4nLRhEw", "node.id":
"OGZ70chtQIOu89uzBphQeA" ,

elasticsearch_1  | "stacktrace":
["org.elasticsearch.ElasticsearchSecurityException: current license is
non-compliant for [security]",

elasticsearch_1  | "at
org.elasticsearch.license.LicenseUtils.newComplianceException(LicenseUtils.java:27)
~[?:?]",

elasticsearch_1  | "at
org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:88)
~[?:?]",

elasticsearch_1  | "at
org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:171)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:149)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:66)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:402)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:390)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:689)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.client.support.AbstractClient$ClusterAdmin.nodesStats(AbstractClient.java:786)
~[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.xpack.monitoring.collector.node.NodeStatsCollector.doCollect(NodeStatsCollector.java:81)
~[x-pack-monitoring-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.xpack.monitoring.collector.Collector.collect(Collector.java:85)
[x-pack-monitoring-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:252)
[x-pack-monitoring-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[?:?]",

elasticsearch_1  | "at
java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]",

elasticsearch_1  | "at
org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
[elasticsearch-7.13.4.jar:7.13.4]",

elasticsearch_1  | "at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[?:?]",

elasticsearch_1  | "at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[?:?]",

elasticsearch_1  | "at java.lang.Thread.run(Thread.java:831) [?:?]"] }

elasticsearch_1  | {"type": "server", "timestamp":
"2021-10-15T23:54:32,479Z", "level": "ERROR", "component":
"o.e.x.s.a.f.SecurityActionFilter", "cluster.name": "docker-cluster", "
node.name": "8bd79f150dae", "message": "blocking [indices:monitor/stats]
operation due to expired license. Cluster health, cluster stats and indices
stats \noperations are blocked on license expiration. All data operations
(read and write) continue to work. \nIf you have a new license, please
update it. Otherwise, please reach out to your support contact.",
"cluster.uuid": "l6Sld-zwTASMTwV4nLRhEw", "node.id":
"OGZ70chtQIOu89uzBphQeA"  }

elasticsearch_1  | {"type": "server", "timestamp":
"2021-10-15T23:54:32,479Z", "level": "ERROR", "component":
"o.e.x.m.c.i.IndexStatsCollector", "cluster.name": "docker-cluster", "
node.name": "8bd79f150dae", "message": "collector [index-stats] failed to
collect data", "cluster.uuid": "l6Sld-zwTASMTwV4nLRhEw", "node.id":
"OGZ70chtQIOu89uzBphQeA" ,


The fix is to exec into the container and run:

curl  -k  -XPOST -u elastic '
https://localhost:9200/_license/start_basic?acknowledge=true' -H
"Content-Type: application/json"

On Fri, Oct 15, 2021 at 7:44 PM Antoine Cotten ***@***.***>
wrote:

> OK the fact that Kibana doesn't start at all is unexpected and worth
> mentioning. Some features are disabled but all components *should* be
> able to run.
>
> Is there any error message in the logs of the Kibana container? Something
> that could help me figure how to assist and what to document?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_deviantony_docker-2Delk_issues_628-23issuecomment-2D944811097&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=C04OxWX74jFKm_XpRq5NMli93L-_KPNo_KtWYeEcyHo&s=sv1L8egTLiBMF42kwOiYqz9VbAFDZQIRvj7_SWxEGAs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMNB64FXOSR3Z7XT3ELTEFLUHC4FDANCNFSM5GC5UNKA&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=C04OxWX74jFKm_XpRq5NMli93L-_KPNo_KtWYeEcyHo&s=qkioUC5EzbPgNnGoTgIYc9FXoDn5nq0R7rtHS_WMnYA&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=C04OxWX74jFKm_XpRq5NMli93L-_KPNo_KtWYeEcyHo&s=pHk4tgT3BBE61K_NpYtCw8o6DEQVnDX_x5-f5JIaSDA&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=C04OxWX74jFKm_XpRq5NMli93L-_KPNo_KtWYeEcyHo&s=z7oQBZByQddgENZpA5zqz5Ch7gzwrMCCM1ktKXZXDgM&e=>.
>
>


-- 


Erik Witkop  |  DOD Systems Engineer | PCNSE CISSP GPEN

Palo Alto Networks  |  Boston, MA |  USA

Mobile: 603-490-3737  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>


<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by e-mail.
Any unauthorized use or distribution of the content of this message is
prohibited.

**Comment by antoineco** [comment] 2021-10-30 16:20
@ewitkop-panw I tried to reproduce this issue by forcing my trial license to expire (essentially by deleting it so it switches to `basic` before the expiry date), but I wasn't able to.

Here is the detail of what I did:

```console
$ curl -D- -X DELETE localhost:9200/_license -u elastic:changeme

HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
content-length: 21

{"acknowledged":true}
```

```console
$ curl -D- localhost:9200/_license -u elastic:changeme

HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
content-length: 371

{
  "license" : {
    "status" : "active",
    "uid" : "1e15e9f9-5ca4-4309-9903-04b4453c6a8e",
    "type" : "basic",
    "issue_date" : "2021-10-30T15:53:53.031Z",
    "issue_date_in_millis" : 1635609233031,
    "max_nodes" : 1000,
    "max_resource_units" : null,
    "issued_to" : "docker-cluster",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}
```

Then I restarted the stack. Kibana started just fine, and I was able to log in:

```
kibana_1         | [2021-10-30T15:58:59.687+00:00][INFO ][status] Kibana is now available (was degraded)
kibana_1         | [2021-10-30T16:05:08.964+00:00][INFO ][plugins.security.routes] Logging in with provider "basic" (basic)
```

![image](https://user-images.githubusercontent.com/3299086/139540431-d33f7244-be29-4a85-b75c-351651acbc97.png)

---

Side note:

I see you didn't fill in any information in your original issue description, although we clearly indicate that it is difficult for us to provide guidance without knowing anything about the runtime environment and the configuration of the stack.

Therefore I am closing the issue for the two following reasons:
- Can't reproduce with the default config
- No information about the user's environment and config

**Closed by antoineco** 2021-10-30 16:20 UTC
Labels: input wanted, kibana, documentation
