### ISSUE TITLE
Kibana returning 503 with message "License is not available"

### ISSUE THREAD

**Issue by gaygayboy** [deviantony/docker-elk#582] opened 2021-03-26 07:56 UTC
#### Docker setup

```console
$ docker-compose logs

[OUTPUT HERE]
```

last one：
![image](https://user-images.githubusercontent.com/26892667/112599997-95b09080-8e4b-11eb-8cbd-3233d4d5ac3c.png)
After a few minutes, this is displayed. I changed "trial" to "basic" in "xpack.license.self_generated.type"

**Comment by antoineco** [comment] 2021-03-26 09:14
@gaygayboy as clearly stated in the issue template, we can't help you without a minimum information. Unfortunately I see absolutely no log in this issue that could allow me to guess where the problem is, so I'm gonna go ahead and close this.

Please reopen once all the requested information has been provided. It will save both of us a lot of time and "ping pong" comments.

**Comment by gaygayboy** [comment] 2021-03-26 09:24
Problem description
Extra information
Stack configuration
Docker setup
$ docker-compose version

ai-dev@aidev:~/wubailong_dev/docker-elk-main$ docker-compose version
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019


[OUTPUT HERE]
Container logs
$ docker-compose logs
logs: https://www.notion.so/quinceywu/docker-logs-0abb70686bab4718a1e4c2fcf28ad71c


[OUTPUT HERE]
last one：
image
After a few minutes, this is displayed. I changed "trial" to "basic" in "xpack.license.self_generated.type"

**Comment by antoineco** [comment] 2021-03-26 09:29
@gaygayboy those logs are incomplete, Elasticsearch hasn't even finished starting yet.

Give it 2-3 minutes please, then post your logs again.

**Comment by gaygayboy** [comment] 2021-03-26 09:34
ai-dev@aidev:~/wubailong_dev/docker-elk-main$ docker-compose up -d
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
docker-elk-main_elasticsearch_1 is up-to-date
docker-elk-main_kibana_1 is up-to-date
docker-elk-main_logstash_1 is up-to-date
ai-dev@aidev:~/wubailong_dev/docker-elk-main$ docker ps
CONTAINER ID   IMAGE                                          COMMAND                  CREATED          STATUS          PORTS                                                                                                                  NAMES
679702247b81   zhocr_web                                      "uvicorn app.run:app…"   10 minutes ago   Up 10 minutes   0.0.0.0:9991->8000/tcp                                                                                                 ocr_api
9690b24f123c   mcr.microsoft.com/onnxruntime/server:latest    "/onnxruntime/server…"   10 minutes ago   Up 10 minutes   0.0.0.0:33322->8001/tcp                                                                                                ocr_direction
00a24c8c2ebb   tensorflow/serving:latest                      "/usr/bin/tf_serving…"   10 minutes ago   Up 10 minutes   0.0.0.0:8502->8500/tcp, 0.0.0.0:8503->8501/tcp                                                                         ocr_text_rec_01
3bc4de856ce4   mcr.microsoft.com/onnxruntime/server:latest    "/onnxruntime/server…"   10 minutes ago   Up 10 minutes   0.0.0.0:43322->8001/tcp                                                                                                ocr_detect
056ffdfa652b   nginx:latest                                   "/docker-entrypoint.…"   10 minutes ago   Up 10 minutes   0.0.0.0:9938->80/tcp, 0.0.0.0:9988->9991/tcp, 0.0.0.0:9968->9992/tcp, 0.0.0.0:9958->9993/tcp, 0.0.0.0:9948->9994/tcp   ocr_nginx
99738c9533f4   tensorflow/serving:latest                      "/usr/bin/tf_serving…"   10 minutes ago   Up 10 minutes   0.0.0.0:8500-8501->8500-8501/tcp                                                                                       ocr_text_rec_00
b1fc55266d90   tensorflow/serving:latest                      "/usr/bin/tf_serving…"   10 minutes ago   Up 10 minutes   8501/tcp, 0.0.0.0:8504->8500/tcp                                                                                       alpha_num
902059c6be02   docker-elk-main_logstash                       "/usr/local/bin/dock…"   53 minutes ago   Up 53 minutes   0.0.0.0:5000->5000/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:9600->9600/tcp, 0.0.0.0:5000->5000/udp                         docker-elk-main_logstash_1
f84266500a24   docker-elk-main_kibana                         "/bin/tini -- /usr/l…"   53 minutes ago   Up 53 minutes   0.0.0.0:5601->5601/tcp                                                                                                 docker-elk-main_kibana_1
2e3203db1190   docker-elk-main_elasticsearch                  "/bin/tini -- /usr/l…"   53 minutes ago   Up 53 minutes   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp                                                                         docker-elk-main_elasticsearch_1
20fa75111c60   transformersner_train                          "/bin/bash"              5 hours ago      Up 5 hours                                                                                                                             transformers_ner_train
639199125c32   python:3.7.9                                   "bash"                   26 hours ago     Up 26 hours     0.0.0.0:9499->5000/tcp                                                                                                 vega
8bc102abfea2   mysql:8.0.18                                   "docker-entrypoint.s…"   28 hours ago     Up 28 hours     33060/tcp, 0.0.0.0:2306->3306/tcp                                                                                      vega_mysql
fa7842dab097   znlh_vrp_api                                   "/bin/sh -c 'while s…"   31 hours ago     Up 31 hours     0.0.0.0:8089->8000/tcp                                                                                                 vrp_api
cc1c0ff0e626   mongo:latest                                   "docker-entrypoint.s…"   3 days ago       Up 3 days       0.0.0.0:27020->27017/tcp                                                                                               mongo_dany
b2abe859235b   img_direction_dany                             "/bin/bash"              5 days ago       Up 5 days                                                                                                                              img_direction_dany_3
b6ca6a09ff25   mongo                                          "docker-entrypoint.s…"   6 days ago       Up 6 days       0.0.0.0:37017->27017/tcp                                                                                               tiejiawang_mongodb
bbae8e6383d1   densenctc_2_dany                               "/bin/bash"              6 days ago       Up 6 days                                                                                                                              densenctc_dany_1
c585057b7b57   doccano/doccano                                "/doccano/tools/run.…"   7 days ago       Up 7 days       0.0.0.0:19888->8000/tcp                                                                                                doccano
98b4daf21d95   tikazyq/crawlab:latest                         "/bin/bash /app/dock…"   7 days ago       Up 7 days       8000/tcp, 0.0.0.0:8080->8080/tcp                                                                                       work
47d4699d18f8   house_monitor_worker                           "/usr/local/bin/nvid…"   7 days ago       Up 7 days       6006/tcp, 8888/tcp, 0.0.0.0:11111->11111/tcp                                                                           house_monitor_worker
df9e17d3e6fc   nginx:latest                                   "/docker-entrypoint.…"   7 days ago       Up 7 days       80/tcp, 0.0.0.0:26888->26888/tcp                                                                                       house_monitor_fileserver
7c5856d0de51   sola97/shadowsocks                             "/entrypoint.sh -t '…"   8 days ago       Up 8 days       0.0.0.0:1080->1080/tcp, 0.0.0.0:1080->1080/udp, 0.0.0.0:6500->6500/tcp, 0.0.0.0:6500->6500/udp                         ss_cn_js
3dc85002048e   tensorflow/tensorflow:1.13.1-gpu-py3-jupyter   "bash -c 'source /et…"   8 days ago       Up 8 days       0.0.0.0:9888->8888/tcp                                                                                                 notebook_notebooks_1
eb792a71ff44   densenctc_1_dany                               "/bin/bash"              9 days ago       Up 8 days                                                                                                                              densenctc_dany_0
a43f3f3f2d43   tensorflow/tensorflow:1.13.1-gpu-py3-jupyter   "bash -c 'source /et…"   3 weeks ago      Up 11 days      0.0.0.0:16006->6006/tcp, 0.0.0.0:9889->8888/tcp                                                                        notebook-gpu_notebooks-tangweikun-gpu2_1
f84717b3e8a1   tikazyq/crawlab:latest                         "/bin/bash /app/dock…"   5 weeks ago      Up 11 days      8000/tcp, 8080/tcp                                                                                                     worker
8c47fa1097f5   redis:latest                                   "docker-entrypoint.s…"   5 weeks ago      Up 11 days      0.0.0.0:16379->6379/tcp                                                                                                ai-dev_redis_1
46cf45a8083a   mongo:latest                                   "docker-entrypoint.s…"   5 weeks ago      Up 11 days      0.0.0.0:27017->27017/tcp                                                                                               ai-dev_mongo_1
2abcf1b3f376   portainer/portainer                            "/portainer"             2 months ago     Up 11 days      0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp                                                                         portainer
ai-dev@aidev:~/wubailong_dev/docker-elk-main$


This is the situation of my docker container and the running situation of docker-compose. 503 will happen a few minutes after I start docker-compose, and then 503. Is it because of my es problem?

**Comment by gaygayboy** [comment] 2021-03-26 09:37
docekr-ps-docker-compose：https://www.notion.so/quinceywu/docker-compose-76ca844f204947ce8a8f48f304e89af2
This is the situation of my docker container and the running situation of docker-compose. 503 will happen a few minutes after I start docker-compose, and then 503. Is it because of my es problem?

**Comment by antoineco** [comment] 2021-03-26 09:37
Those are a list of containers.

What I'm asking for are **logs**.

All commands are described in the template. Please make an effort and simply follow them.

**Comment by antoineco** [comment] 2021-03-26 09:40
And yes, if Elasticsearch hasn't finished starting after 58 min and is not printing any log, you probably have a pretty serious issue with Elasticsearch.

**Comment by gaygayboy** [comment] 2021-03-26 09:46
Later, I will restart docker-compose to try. Although it has been restarted many times, this time I recorded all the docker-compose logs. Please help me solve the 503 problem.

**Comment by antoineco** [comment] 2021-03-29 09:01
@gaygayboy where are we standing with those logs? Any chance you managed to get them?

**Comment by gaygayboy** [comment] 2021-03-29 09:04
Sorry, I refactored the server and ELK service during last weekend, and it is now running normally. Now I am dealing with the issue of how python and kafka are linked with elk. I am very sorry but forgot to close this issue.

**Closed** 2021-03-29 10:05 UTC
Labels: need-info
