### ISSUE TITLE
Error: Storage disk watermark exceeded

### ISSUE THREAD

**Issue by leo4ever** [deviantony/docker-elk#219] opened 2017-12-27 15:37 UTC
I am getting the error below when launching the containers. I was able to start everything fine the very first time, but wanted to delete and recreate the index pattern and started seeing this error message. 

`flood stage disk watermark [95%] exceeded on [2E-4rEiRS1G_2_oztN_guA][2E-4rEi][/usr/share/elasticsearch/data/nodes/0] free: 952.1mb[1.4%], all indices on this node will marked read-only`

**Comment by antoineco** [comment] 2017-12-27 17:26
Your disk (Elasticsearch data volume) is full as the message suggests. The best you can do is extend it or delete your data.

Closing because the issue is not related to the project itself, but feel free to keep discussing below.

**Closed by antoineco** 2017-12-27 17:26 UTC
