### ISSUE TITLE
Following README results in a non fonctionnal stack

### ISSUE THREAD

**Issue by eoli3n** [deviantony/docker-elk#449] opened 2019-11-25 07:49 UTC
### Problem description

I strictly followed documentation and stack is not working

### Extra information

```
~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ docker-compose down -v
Stopping docker-elk_logstash_1      ... done
Stopping docker-elk_kibana_1        ... done
Stopping docker-elk_elasticsearch_1 ... done
Removing docker-elk_logstash_1      ... done
Removing docker-elk_kibana_1        ... done
Removing docker-elk_elasticsearch_1 ... done
Removing network docker-elk_elk
Removing volume docker-elk_elasticsearch

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ cd ..

~/docker-ipt master* root@tspeda-docker-ipt
❯ rm -Rf docker-elk/

~/docker-ipt master* root@tspeda-docker-ipt
❯ git clone https://github.com/deviantony/docker-elk
Clonage dans 'docker-elk'...
remote: Enumerating objects: 1450, done.
remote: Total 1450 (delta 0), reused 0 (delta 0), pack-reused 1450
Réception d'objets: 100% (1450/1450), 345.28 KiB | 1.15 MiB/s, fait.
Résolution des deltas: 100% (560/560), fait.

~/docker-ipt master* root@tspeda-docker-ipt
❯ cd docker-elk

~/docker-ipt/docker-elk master root@tspeda-docker-ipt
❯ ls
docker-compose.yml  docker-stack.yml  elasticsearch/  extensions/  kibana/  LICENSE  logstash/  README.md

~/docker-ipt/docker-elk master root@tspeda-docker-ipt
❯ sed -i 's/trial/basic/' elasticsearch/config/elasticsearch.yml

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ grep basic elasticsearch/config/elasticsearch.yml
xpack.license.self_generated.type: basic

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ docker-compose up -d
Creating network "docker-elk_elk" with driver "bridge"
Creating volume "docker-elk_elasticsearch" with default driver
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_kibana_1        ... done
Creating docker-elk_logstash_1      ... done

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ docker-compose exec -T elasticsearch bin/elasticsearch-setup-passwords auto --batch > passwords

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ sed -i 's/changeme/'(cat passwords | grep "PASSWORD elastic" | awk '{print $4}' )'/' docker-compose.yml

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ cat docker-compose.yml | grep ELASTIC_PASSWORD
      ELASTIC_PASSWORD: HRLj12HpSk8QGbVlP9I3

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ sed -i 's/changeme/'(cat passwords | grep "PASSWORD logstash_system" | awk '{print $4}' )'/' logstash/config/logstash.yml

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ sed -i 's/username: elastic/username: logstash_system/' logstash/config/logstash.yml

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ sed -i 's/changeme/'(cat passwords | grep "PASSWORD kibana" | awk '{print $4}' )'/' kibana/config/kibana.yml

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ sed -i 's/username: elastic/username: kibana/' kibana/config/kibana.yml

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ cat logstash/config/logstash.yml 
---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: 3xHO1i8tMy41ongkVHj4

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ cat kibana/config/kibana.yml 
---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana
elasticsearch.password: J5FKNajJoKEL0o4JV5ub

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt
❯ docker-compose down
Stopping docker-elk_logstash_1      ... done
Stopping docker-elk_kibana_1        ... done
Stopping docker-elk_elasticsearch_1

~/docker-ipt/docker-elk master* root@tspeda-docker-ipt 12s
❯ docker-compose up
Creating network "docker-elk_elk" with driver "bridge"
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_kibana_1        ... done
Creating docker-elk_logstash_1      ... done
Attaching to docker-elk_elasticsearch_1, docker-elk_logstash_1, docker-elk_kibana_1

[.......]

elasticsearch_1  | {"type": "server", "timestamp": "2019-11-22T15:14:32,944Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "a8d7370f972f", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "9cX4uK-sS0qARPRqMHcQnw", "node.id": "wp_o1QpNRgqvvSoGtyePGA"  }
logstash_1       | [2019-11-22T15:14:32,947][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elastic:xxxxxx@elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'"}
elasticsearch_1  | {"type": "server", "timestamp": "2019-11-22T15:14:38,041Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "a8d7370f972f", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "9cX4uK-sS0qARPRqMHcQnw", "node.id": "wp_o1QpNRgqvvSoGtyePGA"  }
logstash_1       | [2019-11-22T15:14:38,044][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elastic:xxxxxx@elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'"}
```
#### Docker setup

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

#### Docker logs

[docker-compose logs](http://ix.io/22NM)

**Comment by antoineco** [comment] 2019-11-25 08:18
Thanks for sharing all those details. I don't see anything obviously wrong in your setup, so I'll try to reproduce and get back to you.

**Comment by eoli3n** [comment] 2019-11-25 08:26
Ok thanks

**Comment by antoineco** [comment] 2019-11-25 08:26
Actually I already found it. The Logstash pipeline also requires credentials for the Elasticsearch output in `logstash/pipeline/logstash.conf`.

We have a note about configuring permissions for the Logstash pipeline in the README, but maybe we should mention more explicitly that the `elastic` user is used by default.

**Comment by eoli3n** [comment] 2019-11-25 08:32
The fact is that i discover elk with your project. So maybe README should be updated in a more explicitly 'step by step' way. I found the line
``Do not use the logstash_system user inside the Logstash pipeline file`` but i didn't know what is pipeline file.

Thanks for your help. Another strange thing is that, the first time i ran the stack, i found a pipeline declaration view in kibana. Now i can't find any logstash configuration view in kibana. Is that normal ?

**Comment by antoineco** [comment] 2019-11-25 08:40
You're absolute right, the instructions should be more clear. I'll reopen your issue so I keep that on my list, and will close it with a PR later today.

Regarding the pipeline view, that's an excellent question. It should be visible with the `basic` license type. The only explanation I could come up with is that Elasticsearch didn't start with the correct license type. If a restart of Elasticsearch + Logstash doesn't solve it, there might be a permission issue with the `logstash_system` user.

**Comment by eoli3n** [comment] 2019-11-25 09:00
You can precise in documentation that ELASTIC_PASSWORD in docker-compose file should be updated too. 

Concerning logstash view, i verified that passwords matches

_passwords file_ 
```
Changed password for user logstash_system
PASSWORD logstash_system = 3xHO1i8tMy41ongkVHj4
```

_logstash/config/logstash.yml_
```
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: 3xHO1i8tMy41ongkVHj4
```

Restated the stack and can't see the view
![img](https://x0.at/d_H.png)

Another thing but maybe i need to open another issue : is there a way to facilitate beats install with your stack ?

**Comment by antoineco** [comment] 2019-11-25 09:19
> You can precise in documentation that ELASTIC_PASSWORD in docker-compose file should be updated too.

Actually this replacement is not needed, the bootstrap password is set [once] (https://github.com/elastic/elasticsearch/blob/2a4e101a/distribution/docker/src/docker/bin/docker-entrypoint.sh#L121-123), and then ignored after the user has set a password for the `elastic` user. I'll also add that the user can delete the env var after generating passwords.

> Concerning logstash view ...

I can't give you any recommendation at that point because I don't use the view myself, but I'll check it out. It could be that you need to send at least one log document and set up an index pattern in order to use it.

> is there a way to facilitate beats install with your stack

There is actually nothing to install, Logstash ships with a `beats` input. All you have to do is configure it inside `pipeline.conf` according to [Beats / Configure the Logstash output](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html).
e.g.
```ruby
input {
  beats {
    port => 5044
  }
}
```

By the way, sorry for missing your questions on Gitter last week, for some reason it notified me only this morning.

**Comment by onlinejudge95** [comment] 2019-11-25 09:19
I am currently facing the same issue, I even tried removing the line
`xpack.security.enabled: true` 
from `./elasticsearch/config/elasticsearch.yml`

**Comment by eoli3n** [comment] 2019-11-25 09:42
@antoineco thx for your help, np for gitter.
I saw logstash view once, but i don't know how. I just wonder why, let me know if you find.

**Comment by antoineco** [comment] 2019-11-25 16:38
I just opened the pull request above ☝️ 

Feel free to leave your comments on it.

**Comment by antoineco** [comment] 2019-11-26 08:27
@eoli3n I can see the _Pipelines_ menu in Kibana's management panel (`http://<stack url>:5601/app/kibana#/management`).

As stupid as it may sound, have you tried a hard refresh of the Kibana app? (Ctrl+Shift+R)

#### 1. With just a change to the license type

```diff
$ git diff
diff --git a/elasticsearch/config/elasticsearch.yml b/elasticsearch/config/elasticsearch.yml
index 39bfd40..cbe96ab 100644
--- a/elasticsearch/config/elasticsearch.yml
+++ b/elasticsearch/config/elasticsearch.yml
@@ -13,6 +13,6 @@ discovery.type: single-node
 ## X-Pack settings
 ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
 #
-xpack.license.self_generated.type: trial
+xpack.license.self_generated.type: basic
 xpack.security.enabled: true
 xpack.monitoring.collection.enabled: true
```
```console
$ docker-compose restart
Restarting docker-elk_logstash_1      ... done
Restarting docker-elk_kibana_1        ... done
Restarting docker-elk_elasticsearch_1 ... done
```

<img src="https://user-images.githubusercontent.com/3299086/69611170-850cc200-102d-11ea-9ed7-1602882a63ad.png" width="100px">

#### 2. With a change to both the license type and users

```diff
$ git diff
diff --git a/elasticsearch/config/elasticsearch.yml b/elasticsearch/config/elasticsearch.yml
index 39bfd40..cbe96ab 100644
--- a/elasticsearch/config/elasticsearch.yml
+++ b/elasticsearch/config/elasticsearch.yml
@@ -13,6 +13,6 @@ discovery.type: single-node
 ## X-Pack settings
 ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
 #
-xpack.license.self_generated.type: trial
+xpack.license.self_generated.type: basic
 xpack.security.enabled: true
 xpack.monitoring.collection.enabled: true
diff --git a/kibana/config/kibana.yml b/kibana/config/kibana.yml
index f9844cd..b4e74ab 100644
--- a/kibana/config/kibana.yml
+++ b/kibana/config/kibana.yml
@@ -9,5 +9,5 @@ xpack.monitoring.ui.container.elasticsearch.enabled: true

 ## X-Pack security credentials
 #
-elasticsearch.username: elastic
-elasticsearch.password: changeme
+elasticsearch.username: kibana
+elasticsearch.password: rjmE2KzYGtEqqQdw65s7
diff --git a/logstash/config/logstash.yml b/logstash/config/logstash.yml
index a48c35f..b2e526e 100644
--- a/logstash/config/logstash.yml
+++ b/logstash/config/logstash.yml
@@ -8,5 +8,5 @@ xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
 ## X-Pack security credentials
 #
 xpack.monitoring.enabled: true
-xpack.monitoring.elasticsearch.username: elastic
-xpack.monitoring.elasticsearch.password: changeme
+xpack.monitoring.elasticsearch.username: logstash_system
+xpack.monitoring.elasticsearch.password: qVanZkuPcf3bbbwhWfNu
diff --git a/logstash/pipeline/logstash.conf b/logstash/pipeline/logstash.conf
index 14c76f8..e5f592a 100644
--- a/logstash/pipeline/logstash.conf
+++ b/logstash/pipeline/logstash.conf
@@ -10,6 +10,6 @@ output {
        elasticsearch {
                hosts => "elasticsearch:9200"
                user => "elastic"
-               password => "changeme"
+               password => "q1d2a5eO0DVmNXW7F66v"
        }
 }
```
```console
$ docker-compose restart
Restarting docker-elk_logstash_1      ... done
Restarting docker-elk_kibana_1        ... done
Restarting docker-elk_elasticsearch_1 ... done
```

<img src="https://user-images.githubusercontent.com/3299086/69611170-850cc200-102d-11ea-9ed7-1602882a63ad.png" width="100px">

**Comment by eoli3n** [comment] 2019-11-26 13:44
That's exactly what i did, and yes i refreshed, so i don't know :/
But that's not important, i work in my shell, thx for your help.

**Closed** 2019-11-26 13:56 UTC
Labels: documentation
