### ISSUE TITLE
Linking the tls to wildcard certificate

### ISSUE THREAD

**Issue by crimson-med** [deviantony/docker-elk#846] opened 2023-03-29 11:19 UTC
### Problem description

I'm trying to deploy the stack on a domain: watch.test.com
We already have a wildcard certificate for that domain

I have changed the kibana configuration to reflect the following:

```yml
server.publicBaseUrl: https://watch.test.com:5601
server.ssl.enabled: true
# Following cert is the wildacrad and its key
server.ssl.certificate: config/kibana.crt 
server.ssl.key: config/kibana.key
xpack.fleet.agents.fleet_server.hosts: [ https://watch.test.com:8220 ]

xpack.fleet.outputs:
  - id: fleet-default-output
    name: default
    type: elasticsearch
    hosts: [ https://watch.test.com:9200 ]
    # Set to output of 'docker-compose up tls'. Example:
    #ca_trusted_fingerprint: bd66954aefe4f89c7f9eaae2222aaa54cde39bd32bb6445d73d397a12119dea8
    is_default: true
    is_default_monitoring: true
```

I'm not sure here if the CA should still be the one from tls command or if I should leave it commented

When I try to connect the fleet server i get the following:

```bash
Elastic Agent will be installed at /opt/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:Y
{"log.level":"info","@timestamp":"2023-03-29T10:58:46.026Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":407},"message":"Generating self-signed certificate for Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-29T10:58:48.663Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":803},"message":"Fleet Server - Error - x509: certificate is valid for localhost, elasticsearch, not watch.test.com","ecs.version":"1.6.0"}
Error: fleet-server failed: context canceled
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.6/fleet-troubleshooting.html
Error: enroll command failed with exit code: 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.6/fleet-troubleshooting.html
```

Do I simply need to replace the `tls/ca/ca.crt` `tls/ca/ca.key` `tls/fleet-server/fleet-server.crt` `tls/fleet-server/fleet-server.key` with the wildcard? 

Agents will need to ping: watch.test.com as they will be spread across various networks.

**Comment by antoineco** [comment] 2023-03-29 13:17
If you have a wildcard certificate for the domain, you need to skip the generation of self signed certificates entirely (`docker-compose up tls`) and, for example, create the following file tree:

```
tls
├── ca
│   └── my-ca.crt
└── certs
    ├── my-wildcart.crt
    └── my-wildcard.key
```

1. If you obtained the certificate from a public authority such as _Let's Encrypt_, `my-ca.crt` is the CA certificate of this authority.
Similarly, if the certificate was provided by a private authority such as a corporate PKI, `my-ca.crt` is the CA certificate of this authority.

    The files under `certs/` are the certificate and its private key respectively.

    **You do NOT need to keep the CA key in the repository.** This key is only needed to sign new certificates, which is irrelevant here since certificates aren't signed by docker-elk.

1. You then need to update the paths to those certificates and key in all your Compose files. E.g. `- ./tls/certs/ca/my-ca.crt:/usr/share/elastic-agent/ca.crt:ro`.

1. For Elastic Agent, please beware that you need to [provide the fingerprint](https://github.com/deviantony/docker-elk/tree/tls/extensions/fleet#ca-certificate-fingerprint) (via Kibana) of the CA certificate used by Elasticsearch, not the CA certificate itself, unlike with other components. It can be obtained with the command `openssl x509 -fingerprint -sha256 -noout -in tls/certs/ca/my-ca.crt`. You need to remove all colon characters (`:`) from the output.

**Comment by antoineco** [comment] 2023-03-30 09:54
That's surprising indeed. I see that the error is `ECONNREFUSED` with the messages `unable to get issuer certificate` two lines below. Could it be a firewall issue?

The fact that Kibana prints the IP and not the hostname in its logs is not an indicator of a problem from my experience. It does correctly check that the hostname presented by the certificate matches. In this case, the issue is probably elsewhere.

**Comment by crimson-med** [comment] 2023-03-30 10:05
I have all the proper ports opened on the firewall

![Screenshot 2023-03-30 at 6 02 35 PM](https://user-images.githubusercontent.com/28290546/228801989-01921aaf-3d2f-4049-9a33-5265e859b948.png)

If I manually go on my browser to: https://watch.test.com:9200 I'm prompted with the username password and if they are correct I do reach the landing endpoint:

![Screenshot 2023-03-30 at 6 05 05 PM](https://user-images.githubusercontent.com/28290546/228802594-b7fe9cc9-1e9f-42dd-adfc-20ed96ba2653.png)

**Comment by antoineco** [comment] 2023-03-30 10:12
Possibly a misconfiguration of the CA certificate then?

https://github.com/deviantony/docker-elk/blob/ff28dec137f889f7159762d6d005a389cc44cdc8/kibana/config/kibana.yml#L22-L25

I can't think about anything else right now.

**Comment by crimson-med** [comment] 2023-03-30 10:18
For the CA just to confirm;

We have our certificate, then we have entity sectigo in UK then we have the final in US.
Our chain certificate basically has 3 in one. Does the CA need to be both above or just the very root one?

**Comment by antoineco** [comment] 2023-03-30 10:40
The CA certificate file should contain the entire chain, unless some of those certificates are already part of the Kibana container image.

If all CAs in the chain are well known public CAs, you don't even need to provide a CA certificate for Kibana to trust Elasticsearch.

**Comment by antoineco** [comment] 2023-03-30 18:36
Logstash is getting a permission error, unrelated to TLS.

**Comment by antoineco** [comment] 2023-04-04 17:21
Closing because a working solution to the original problem was provided.

For the resolution of authorization issues, I recommend double checking the effective permissions of the affected users. For example, ensure that the user configured in the Logstash pipeline has authority on custom Elasticsearch indices, etc.

**Closed by antoineco** 2023-04-04 17:21 UTC
