### ISSUE TITLE
Encountered a retryable error.

### ISSUE THREAD

**Issue by farrukhahmed4220** [deviantony/docker-elk#444] opened 2019-11-03 12:30 UTC
### Problem description

Well I'm new to ELK.  I'm following your instructions. There is an issue while injecting data. I have used the command below. and then I checked the docker logs of logstash. It shows the following.

#### Command

``` 
nc localhost 5000 < /var/log/messages
```

```
<!-- Replace this comment with the full output of the `docker-compose version` command. -->
```

#### Docker logs

```
 [2019-11-03T11:47:54,477][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch bulk_path=>"/_monitoring/bulk?system_id=logstash&system_api_version=7&interval=1s", password=><password>, hosts=>[//elasticsearch:9200], sniffing=>false, manage_template=>false, id=>"4627c0f55574754af29573f21e0f7f8f8d9743338e455e0a8da1122ae2e2f61f", user=>"logstash_system", document_type=>"%{[@metadata][document_type]}", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_d91bf20d-2777-41aa-9c5c-0dafe7c1588c", enable_metric=>true, charset=>"UTF-8">, workers=>1, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, ilm_enabled=>"auto", ilm_rollover_alias=>"logstash", ilm_pattern=>"{now/d}-000001", ilm_policy=>"logstash-policy", action=>"index", ssl_certificate_verification=>true, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
[2019-11-03T11:47:54,641][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logstash_system:xxxxxx@elasticsearch:9200/]}}
[2019-11-03T11:47:54,726][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://logstash_system:xxxxxx@elasticsearch:9200/"}
[2019-11-03T11:47:54,788][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>7}
[2019-11-03T11:47:54,788][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2019-11-03T11:47:54,875][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//elasticsearch:9200"]}
[2019-11-03T11:47:54,906][INFO ][logstash.javapipeline    ] Starting pipeline {:pipeline_id=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>2, :thread=>"#<Thread:0x635f1c75 run>"}
[2019-11-03T11:47:55,074][INFO ][logstash.javapipeline    ] Pipeline started {"pipeline.id"=>".monitoring-logstash"}
[2019-11-03T11:47:55,193][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:main, :".monitoring-logstash"], :non_running_pipelines=>[]}
[2019-11-03T11:47:56,714][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2019-11-03T11:51:01,394][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"http://elasticsearch:9200/_bulk"}
```

Here is my logstash/pipeline/logstash.conf:
####logstash.conf 
```
input {
        tcp {
                port => 5000
        }
}

## Add your filters / logstash plugins configuration here

filter {
  if [type] == "syslog" {
    grok {
      match => {
         "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}"
      }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    syslog_pri { }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
     }
  }
}

output {
        elasticsearch {
                hosts => "elasticsearch:9200"
                index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
                user => "logstash_system"
                password => "*********"
        }
}
```

and logstash/config/logstash.yml:
```
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "elasticsearch:9200" ]
## X-Pack security credentials
#
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: **********
```

**Comment by antoineco** [comment] 2019-11-03 14:18
The permission issue is because you're using the `logstash_system` user in your Logstash pipeline, whereas this user doesn't have enough permissions to create indices or even read/write to/from them.

From the README:
> Do not use the `logstash_system` user inside the Logstash pipeline file, it does not have sufficient permissions to create indices. [...]

**Comment by farrukhahmed4220** [comment] 2019-11-04 10:52
Thanks... it worked for me...

But now I want to collect my E-commerce web-app server and web-mail server logs through Beat... and I don't want to containerize the Beat, I want to do it in a traditional way... 
Can you please help me out, configuring Beat pushing logs to logstash.

PS: I want to deploy ELK on Amazon EC2 instance, later...

**Comment by antoineco** [comment] 2019-11-04 11:29
Sure, there is absolutely no need to containerize Beats since it's not part of the ELK stack.

1. First of all you need to add a Beats `input` in your Logstash pipeline: [Logstash / Beats input plugin](https://www.elastic.co/guide/en/logstash/7.4/plugins-inputs-beats.html)
    ```config
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        # username, password, ...
      }
    }
    ```
1. Then just configure a Beats `output` to Logstash: [Beats / Configure the Logstash output](https://www.elastic.co/guide/en/beats/filebeat/7.4/logstash-output.html)
    ```
    output.logstash:
      hosts: ["<address of your ELK stack>:5044"]
    ```

**Comment by farrukhahmed4220** [comment] 2019-11-05 15:23
Thanks.. It worked for me...

Now Beat are finely pushing forward logs to logstash...
And now I want to add ElastAlert for Email alerting...
How do I configure ElastAlert?

**Comment by antoineco** [comment] 2019-11-05 16:01
Glad the issue is solved! For questions about third-party integrations, I suggest you 
1. [read the docs](https://elastalert.readthedocs.io/en/latest/), they usually contain a lot of useful information
2. ask experts at https://discuss.elastic.co/ if you can't find your answer in the docs

Closing

**Closed by antoineco** 2019-11-05 16:01 UTC
Labels: documentation, question
