### ISSUE TITLE
sry,503

### ISSUE THREAD

**Issue by gaygayboy** [deviantony/docker-elk#583] opened 2021-03-26 09:25 UTC
Problem description
Extra information
Stack configuration
Docker setup
$ docker-compose version

ai-dev@aidev:~/wubailong_dev/docker-elk-main$ docker-compose version
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l 10 Sep 2019

[OUTPUT HERE]
Container logs
$ docker-compose logs
logs: https://www.notion.so/quinceywu/docker-logs-0abb70686bab4718a1e4c2fcf28ad71c

[OUTPUT HERE]
last one：
image
After a few minutes, this is displayed. I changed "trial" to "basic" in "xpack.license.self_generated.type"

**Comment by antoineco** [comment] 2021-03-26 09:29
Duplicate of #582

**Closed by antoineco** 2021-03-26 09:29 UTC
