### ISSUE TITLE
Downgrading to Java 8

### ISSUE THREAD

**Issue by tranv94** [deviantony/docker-elk#294] opened 2018-07-17 18:51 UTC
Hi, based on the discussion [here](https://github.com/floragunncom/search-guard/issues/514) it was discovered that the docker image is using Java 10, which breaks for searchguard. Is it possible to temporarily downgrade it to support searchguard until they are up to speed?
I also confirmed that the docker image is running Java 10.

**Comment by antoineco** [comment] 2018-07-19 21:32
While this is possible, we'd have to maintain and host our own base images for this. Not sure if any of us has time to dedicate to this activity. 

What would you suggest?

**Comment by tranv94** [comment] 2018-07-24 05:08
Hmm unfortunate. I'm quite new to docker so I don't think I'd be able to even if I wanted to.

**Comment by antoineco** [comment] 2018-08-14 10:55
Supporting only Java 7 and 8 sounds like a bit limitation to me, considering the current release cycle of Java SE. On the other hand we do maintain a branch with Search Guard, so let's see if we can hack something until Java 9+ is supported.

**Comment by antoineco** [comment] 2019-04-04 10:54
@tranv94 the SG developers said they couldn't reproduce the LDAP issue in the referenced discussion. What's the current situation for you?

**Comment by antoineco** [comment] 2019-04-26 08:43
Closing (see previous comment)

**Closed by antoineco** 2019-04-26 08:43 UTC
Labels: search-guard
