### ISSUE TITLE
docker container elasticsearch is unhealthy

### ISSUE THREAD

**Issue by ZTurboX** [deviantony/docker-elk#966] opened 2024-03-11 08:11 UTC
### Problem description

docker container elasticsearch unhealthy
![image](https://github.com/deviantony/docker-elk/assets/5669444/e439506f-e8d2-4483-b95d-c6770dec22f5)

but http://localhost:9200/_cat/health  is green, 
![image](https://github.com/deviantony/docker-elk/assets/5669444/4bf35728-4ac8-46f8-aaff-d582d775afcf)

and can can use elasticsearch and kibana

#### Stack configuration

no changes

#### Docker setup
![image](https://github.com/deviantony/docker-elk/assets/5669444/34611fea-07bf-459e-928e-eb784a6312b5)

#### Container logs
![image](https://github.com/deviantony/docker-elk/assets/5669444/b5fd1369-822b-4cc1-9a0d-ff383f9af7ee)

**Comment by antoineco** [comment] 2024-03-11 08:20
Thanks for your report.

I'm a bit confused, you say
> no changes

But the cluster name is `elasticsearch`, which is not the name of our cluster:

https://github.com/deviantony/docker-elk/blob/212f55885326dae0565999c20908a0bc7107ad51/elasticsearch/config/elasticsearch.yml#L5

**Comment by ZTurboX** [comment] 2024-03-11 08:28
> Thanks for your report.
> 
> I'm a bit confused, you say
> 
> > no changes
> 
> But the cluster name is `elasticsearch`, which is not the name of our cluster:
> 
> https://github.com/deviantony/docker-elk/blob/212f55885326dae0565999c20908a0bc7107ad51/elasticsearch/config/elasticsearch.yml#L5

cluster.name  change to elasticsearch

**Comment by antoineco** [comment] 2024-03-11 08:35
"unhealthy" means that you added a health check.
docker-elk doesn't have health checks.

**Comment by antoineco** [comment] 2024-03-29 12:04
Closing because the issue is clearly not about docker-elk, but about another Elasticsearch-in-Docker type of setup.

**Closed by antoineco** 2024-03-29 12:04 UTC
