### ISSUE TITLE
sgadmin.sh killed in Docker

### ISSUE THREAD

**Issue by chersicm** [deviantony/docker-elk#207] opened 2017-12-05 11:13 UTC
See [issue](https://github.com/floragunncom/search-guard/issues/421) on Search Guard repo.

**Comment by antoineco** [comment] 2017-12-12 17:00
The maintainer in the referenced issue couldn't reproduce with the provided files, so this is most likely related to insufficient resources, or something else outside our control.
Closing.

**Closed by antoineco** 2017-12-12 17:00 UTC
