### ISSUE TITLE
Apostrophes in passwords with Compose versions below v1.26.0

### ISSUE THREAD

**Issue by eNkkkk** [deviantony/docker-elk#698] opened 2022-04-08 20:44 UTC
### Problem description

The default passwords in the .env file are **'changeme'**: when replacing the default passwords with the newly generated secrets, you **must** remove the apostrophes too, adding your new password in between them will break everything, as the containers will ingest **'secret'** (apostrophes included).

### Extra information

```
$ docker exec -it docker-elk_logstash_1 /bin/bash
$ echo $LOGSTASH_INTERNAL_PASSWORD
'secret'
```

**Comment by antoineco** [comment] 2022-04-08 21:53
Only if you use a version of Compose below v1.26.0, which we don't support for this exact reason (ref. https://github.com/deviantony/docker-elk/issues/677#issuecomment-1054213030 + README).

This is a known issue in versions between v1.22.0 and v1.25.5

Duplicate of #696

**Closed** 2022-06-03 09:20 UTC
Labels: compose
